### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [rudolfbyker/lpsd#3]
Hello,

thanks for your great work translating the lpsd code to python! I'm interested in using lpsd in an open source project - is your code licensed as BSD as well?

**Comment by rudolfbyker** [comment]
I'll put any permissive license on it that you need. Which BSD license did you have in mind? I'm not well acquainted with those. I usually make most of my stuff available under the MIT license.

**Comment by rudolfbyker** [comment]
I'm also not sure whether we need permission from the original author of the `.m` files to do this. His repo does not have a license file, either. Maybe I should open a PR with the original repo.

**Comment by rudolfbyker** [comment]
Oh and see https://github.com/tobin/lpsd/issues/1

**Comment by hermitdemschoenenleben** [comment]
> I'll put any permissive license on it that you need. Which BSD license did you have in mind?

that is great, thank you :) MIT license would be great of course but as tobin's code is BSD it's probably not possible. But for me any BSD license is ok (3-clause BSD seems to be the most common one afaik)

**Comment by rudolfbyker** [comment]
As far as I can see, there is nothing preventing me from releasing this under MIT license. Enjoy.
