### ISSUE TITLE
Putting package on pypi

### ISSUE THREAD

**Issue by bleykauf** [rudolfbyker/lpsd#7]
Hey, thanks for inviting me to work on this repo, @rudolfbyker.

I would say that we move this package to pypi for easy installation.

The way I do it, is using github workflows. I can take care of setting this up. Than each time a new version is tagged, it is automatically moved to pypi.

Since I do not have full access to the repository, I cannot add security tokens. So in order for this to work, you would need to get an account on pypi.org, create a token with full access (this can later be changed to a more restrictive one), copy it and save it in github under "Settings" -> "Secrets" -> "Repository Secrets". Please save it under the name "PYPI_PASSWORD". Once you have done that please tell me and we start the process.

Alternatively, I could also do this from my forked repo. Credit to you as the main author is of course retained through github history and in the `setup.cfg`. What do you think?

**Comment by rudolfbyker** [comment]
I see two options here:

1. I publish this on PyPi
2. I transfer ownership of the repo to you

I have done 1 (with other projects), but I'm not actually sure if 2 is possible. I don't have much of an interest in maintaining this repository any more, so I do prefer 2.

**Comment by bleykauf** [comment]
2 would be fine by me. I do actually think it is possible to transfer a personal repository, see https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

I renamed my fork so I do have the namespace available. So you can go ahead and transfer it and I will be happy to maintain it :)

**Comment by rudolfbyker** [comment]
I think you will have to remove your fork completely:

> The target account must not have a repository with the same name, or a fork in the same network.

Or we should somehow un-fork this (or just copy the files to a new repository), because we now have 0% overlap with the original repository, and that's now how forks are supposed to work.

So my third suggestion would be: Copy the code to a new repo, and maybe call it something like py-lpsd, just to be specific. (Obviously on PyPi it could still be called just `lpsd`). Then I will delete this one.

**Comment by bleykauf** [comment]
I do agree that the fork from the original matlab code doesn't make too much sense at this point. 

Would you then simply start from the current state of the repo (without the history) or retain history including the matlab code in the older versions?

In case of the latter, you would apparently have to ask a github bot to unfork it (https://ralphjsmit.com/unfork-github-repo). In the other case it is probably easier if I simply open a new repo, just copy all the files and make a first commit. Credit to you and to @conradzim would still be in the LICENSE file.

**Comment by rudolfbyker** [comment]
> simply open a new repo, just copy all the files and make a first commit

Let's do this. History is not needed.

**Comment by rudolfbyker** [comment]
Maybe include a link in the README to https://github.com/tobin/lpsd under a heading like "Implementations in other languages"?

**Comment by bleykauf** [comment]
The repo is now at https://github.com/bleykauf/py-lpsd.

Maybe add a line to the readme here:

```
:no_entry: [DEPRECATED] It is now maintained at [py-lpsd](https://github.com/bleykauf/py-lpsd).
```

**Comment by bleykauf** [comment]
So now available on https://pypi.org/project/lpsd/

Thanks for the peaceful transition of power (spectral density)! :)
